version: '3.8'

services:
  php-apache:
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - ./php/www:/var/www/html
    networks:
      - net-web
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: azerty
    volumes:
      - mysql_backup:/var/lib/mysql
    networks:
      - net-db
      - net-web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: azerty
    networks:
      - net-db
    depends_on:
      - mysql

networks:
  net-db:
  net-web:

volumes:
  mysql_backup:

